export default [
  {
    name: "来一碗麻辣烫",
    address: "广东省广州市越秀区中山五路219号华联购物中心F1",
    id: 1,
    latitude: 23.12497,
    longitude: 113.26308,
    location: [113.26308, 23.12497],
    phone: "13437850035",
    category: "快餐便当/简餐",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5a5859a19c2bc57d52df30b3",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5a5859a19c2bc57d52df30b2",
      },
      {
        description: "该商家支持开发票，请在下单时填写好发票抬头",
        icon_color: "999999",
        icon_name: "票",
        id: 4,
        name: "开发票",
        _id: "5a5859a19c2bc57d52df30b1",
      },
    ],
    status: 1,
    recent_order_num: 106,
    rating_count: 961,
    rating: 4.7,
    promotion_info: "欢迎光临，用餐高峰请提前下单，谢谢",
    piecewise_agent_fee: { tips: "配送费约¥5" },
    opening_hours: ["8:30/20:30"],
    license: {
      catering_service_license_image: "160e91e17fa2164.png",
      business_license_image: "160e91e0a9f2163.png",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_1.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 20,
    float_delivery_fee: 5,
    distance: "9.1公里",
    order_lead_time: "26分钟",
    description: "sad",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [],
    __v: 0,
  },
  {
    name: "地道味麻辣香锅",
    address: "阿联酋防守打法手动阀",
    id: 3269,
    latitude: 22.784219,
    longitude: 113.836478,
    location: [113.76077, 34.73822],
    phone: "110233qaqqq是打发的所发生的发地方广胜多负少东省浮动三个11236",
    category: "小吃夜宵/烧烤",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5bfc9a30d51a913e8655d397",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5bfc9a30d51a913e8655d396",
      },
      {
        description: "该商家支持开发票，请在下单时填写好发票抬头",
        icon_color: "999999",
        icon_name: "票",
        id: 4,
        name: "开发票",
        _id: "5bfc9a30d51a913e8655d395",
      },
    ],
    status: 0,
    recent_order_num: 100,
    rating_count: 218,
    rating: 5,
    promotion_info: "欢迎光临，用餐高峰请提前下单，谢谢",
    piecewise_agent_fee: { tips: "配送费约¥5" },
    opening_hours: ["06:30/09:00"],
    license: {
      catering_service_license_image: "",
      business_license_image: "",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_2.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 20,
    float_delivery_fee: 5,
    distance: "85公里",
    order_lead_time: "1小时14分钟",
    description: " 欢迎购买本店招牌菜：肉蛋葱鸡22阿斯顿发发发士大夫是",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [
      {
        icon_name: "减",
        name: "满减优惠",
        description: "满30减5，满60减8",
        icon_color: "f07373",
        id: 1,
        _id: "5bfc9a30d51a913e8655d398",
      },
    ],
    __v: 0,
  },
  {
    name: "健康早餐油条豆浆",
    address: "上海市浦东新区人民东路",
    id: 3276,
    latitude: 31.049617,
    longitude: 121.768129,
    location: [104.073498, 30.697163],
    phone: "150809608",
    category: "甜品饮品",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5bfcbf78d51a913e8655d4f4",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5bfcbf78d51a913e8655d4f3",
      },
      {
        description: "该商家支持开发票，请在下单时填写好发票抬头",
        icon_color: "999999",
        icon_name: "票",
        id: 4,
        name: "开发票",
        _id: "5bfcbf78d51a913e8655d4f2",
      },
    ],
    status: 1,
    recent_order_num: 831,
    rating_count: 482,
    rating: 4.1,
    promotion_info: "欢迎光临，用餐高峰请提前下单，谢谢",
    piecewise_agent_fee: { tips: "配送费约¥5" },
    opening_hours: ["8:30/20:30"],
    license: {
      catering_service_license_image: "",
      business_license_image: "",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_3.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 20,
    float_delivery_fee: 5,
    distance: "1405.4公里",
    order_lead_time: "14小时59分钟",
    description: "vue",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [
      {
        icon_name: "减",
        name: "满减优惠",
        description: "满30减5，满60减8",
        icon_color: "f07373",
        id: 1,
        _id: "5bfcbf78d51a913e8655d4f5",
      },
    ],
    __v: 0,
  },
  {
    name: "张姐烤肉饭",
    address: "rqwerqwer",
    id: 3278,
    latitude: 23.031723,
    longitude: 113.159088,
    location: [114.045515, 22.609881],
    phone: "13526347214",
    category: "快餐便当/简餐",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5bfcfda5d51a913e8655d735",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5bfcfda5d51a913e8655d734",
      },
    ],
    status: 1,
    recent_order_num: 601,
    rating_count: 909,
    rating: 4.3,
    promotion_info: "12345",
    piecewise_agent_fee: { tips: "配送费约¥1" },
    opening_hours: ["17:00/23:15"],
    license: {
      catering_service_license_image: "167543e718022786.jpeg",
      business_license_image: "167543e555722785.jpeg",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_4.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 5,
    float_delivery_fee: 1,
    distance: "23.4公里",
    order_lead_time: "35分钟",
    description: "无",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [
      {
        icon_name: "减",
        name: "满减优惠",
        description: "满30减5，满60减8",
        icon_color: "f07373",
        id: 1,
        _id: "5bfcfda5d51a913e8655d737",
      },
      {
        icon_name: "新",
        name: "新用户立减",
        description: "新用户ji-----",
        icon_color: "70bc46",
        id: 2,
        _id: "5bfcfda5d51a913e8655d736",
      },
    ],
    __v: 0,
  },
  {
    name: "萨沐丁",
    address: "广东省佛山市南海区 顶顶顶v佛挡杀佛",
    id: 3281,
    latitude: 39.159705,
    longitude: 117.14878,
    location: [116.436501, 39.950855],
    phone: "777积分工会法规股份合1计",
    category: "异国料理/披萨意面",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5bfd02ded51a913e8655d7b9",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5bfd02ded51a913e8655d7b8",
      },
      {
        description: "该商家支持开发票，请在下单时填写好发票抬头",
        icon_color: "999999",
        icon_name: "票",
        id: 4,
        name: "开发票",
        _id: "5bfd02ded51a913e8655d7b7",
      },
    ],
    status: 0,
    recent_order_num: 636,
    rating_count: 247,
    rating: 4.6,
    promotion_info: "欢迎光临，用餐高峰请提前下单，谢谢",
    piecewise_agent_fee: { tips: "配送费约¥5" },
    opening_hours: ["8:30/20:30"],
    license: {
      catering_service_license_image: "",
      business_license_image: "",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_5.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 20,
    float_delivery_fee: 5,
    distance: "2051.7公里",
    order_lead_time: "21小时43分钟",
    description: "能能能能能能能能能能能",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [
      {
        icon_name: "减",
        name: "满减优惠",
        description: "满30减5，满60减8",
        icon_color: "f07373",
        id: 1,
        _id: "5bfd02ded51a913e8655d7ba",
      },
    ],
    __v: 0,
  },
  {
    name: "来一碗麻辣烫",
    address: "广东省广州市越秀区中山五路219号华联购物中心F1",
    id: 1,
    latitude: 23.12497,
    longitude: 113.26308,
    location: [113.26308, 23.12497],
    phone: "13437850035",
    category: "快餐便当/简餐",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5a5859a19c2bc57d52df30b3",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5a5859a19c2bc57d52df30b2",
      },
      {
        description: "该商家支持开发票，请在下单时填写好发票抬头",
        icon_color: "999999",
        icon_name: "票",
        id: 4,
        name: "开发票",
        _id: "5a5859a19c2bc57d52df30b1",
      },
    ],
    status: 1,
    recent_order_num: 106,
    rating_count: 961,
    rating: 4.7,
    promotion_info: "欢迎光临，用餐高峰请提前下单，谢谢",
    piecewise_agent_fee: { tips: "配送费约¥5" },
    opening_hours: ["8:30/20:30"],
    license: {
      catering_service_license_image: "160e91e17fa2164.png",
      business_license_image: "160e91e0a9f2163.png",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_1.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 20,
    float_delivery_fee: 5,
    distance: "9.1公里",
    order_lead_time: "26分钟",
    description: "sad",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [],
    __v: 0,
  },
  {
    name: "地道味麻辣香锅",
    address: "阿联酋防守打法手动阀",
    id: 3269,
    latitude: 22.784219,
    longitude: 113.836478,
    location: [113.76077, 34.73822],
    phone: "110233qaqqq是打发的所发生的发地方广胜多负少东省浮动三个11236",
    category: "小吃夜宵/烧烤",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5bfc9a30d51a913e8655d397",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5bfc9a30d51a913e8655d396",
      },
      {
        description: "该商家支持开发票，请在下单时填写好发票抬头",
        icon_color: "999999",
        icon_name: "票",
        id: 4,
        name: "开发票",
        _id: "5bfc9a30d51a913e8655d395",
      },
    ],
    status: 0,
    recent_order_num: 100,
    rating_count: 218,
    rating: 5,
    promotion_info: "欢迎光临，用餐高峰请提前下单，谢谢",
    piecewise_agent_fee: { tips: "配送费约¥5" },
    opening_hours: ["06:30/09:00"],
    license: {
      catering_service_license_image: "",
      business_license_image: "",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_2.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 20,
    float_delivery_fee: 5,
    distance: "85公里",
    order_lead_time: "1小时14分钟",
    description: " 欢迎购买本店招牌菜：肉蛋葱鸡22阿斯顿发发发士大夫是",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [
      {
        icon_name: "减",
        name: "满减优惠",
        description: "满30减5，满60减8",
        icon_color: "f07373",
        id: 1,
        _id: "5bfc9a30d51a913e8655d398",
      },
    ],
    __v: 0,
  },
  {
    name: "健康早餐油条豆浆",
    address: "上海市浦东新区人民东路",
    id: 3276,
    latitude: 31.049617,
    longitude: 121.768129,
    location: [104.073498, 30.697163],
    phone: "150809608",
    category: "甜品饮品",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5bfcbf78d51a913e8655d4f4",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5bfcbf78d51a913e8655d4f3",
      },
      {
        description: "该商家支持开发票，请在下单时填写好发票抬头",
        icon_color: "999999",
        icon_name: "票",
        id: 4,
        name: "开发票",
        _id: "5bfcbf78d51a913e8655d4f2",
      },
    ],
    status: 1,
    recent_order_num: 831,
    rating_count: 482,
    rating: 4.1,
    promotion_info: "欢迎光临，用餐高峰请提前下单，谢谢",
    piecewise_agent_fee: { tips: "配送费约¥5" },
    opening_hours: ["8:30/20:30"],
    license: {
      catering_service_license_image: "",
      business_license_image: "",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_3.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 20,
    float_delivery_fee: 5,
    distance: "1405.4公里",
    order_lead_time: "14小时59分钟",
    description: "vue",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [
      {
        icon_name: "减",
        name: "满减优惠",
        description: "满30减5，满60减8",
        icon_color: "f07373",
        id: 1,
        _id: "5bfcbf78d51a913e8655d4f5",
      },
    ],
    __v: 0,
  },
  {
    name: "张姐烤肉饭",
    address: "rqwerqwer",
    id: 3278,
    latitude: 23.031723,
    longitude: 113.159088,
    location: [114.045515, 22.609881],
    phone: "13526347214",
    category: "快餐便当/简餐",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5bfcfda5d51a913e8655d735",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5bfcfda5d51a913e8655d734",
      },
    ],
    status: 1,
    recent_order_num: 601,
    rating_count: 909,
    rating: 4.3,
    promotion_info: "12345",
    piecewise_agent_fee: { tips: "配送费约¥1" },
    opening_hours: ["17:00/23:15"],
    license: {
      catering_service_license_image: "167543e718022786.jpeg",
      business_license_image: "167543e555722785.jpeg",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_4.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 5,
    float_delivery_fee: 1,
    distance: "23.4公里",
    order_lead_time: "35分钟",
    description: "无",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [
      {
        icon_name: "减",
        name: "满减优惠",
        description: "满30减5，满60减8",
        icon_color: "f07373",
        id: 1,
        _id: "5bfcfda5d51a913e8655d737",
      },
      {
        icon_name: "新",
        name: "新用户立减",
        description: "新用户ji-----",
        icon_color: "70bc46",
        id: 2,
        _id: "5bfcfda5d51a913e8655d736",
      },
    ],
    __v: 0,
  },
  {
    name: "萨沐丁",
    address: "广东省佛山市南海区 顶顶顶v佛挡杀佛",
    id: 3281,
    latitude: 39.159705,
    longitude: 117.14878,
    location: [116.436501, 39.950855],
    phone: "777积分工会法规股份合1计",
    category: "异国料理/披萨意面",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5bfd02ded51a913e8655d7b9",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5bfd02ded51a913e8655d7b8",
      },
      {
        description: "该商家支持开发票，请在下单时填写好发票抬头",
        icon_color: "999999",
        icon_name: "票",
        id: 4,
        name: "开发票",
        _id: "5bfd02ded51a913e8655d7b7",
      },
    ],
    status: 0,
    recent_order_num: 636,
    rating_count: 247,
    rating: 4.6,
    promotion_info: "欢迎光临，用餐高峰请提前下单，谢谢",
    piecewise_agent_fee: { tips: "配送费约¥5" },
    opening_hours: ["8:30/20:30"],
    license: {
      catering_service_license_image: "",
      business_license_image: "",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_5.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 20,
    float_delivery_fee: 5,
    distance: "2051.7公里",
    order_lead_time: "21小时43分钟",
    description: "能能能能能能能能能能能",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [
      {
        icon_name: "减",
        name: "满减优惠",
        description: "满30减5，满60减8",
        icon_color: "f07373",
        id: 1,
        _id: "5bfd02ded51a913e8655d7ba",
      },
    ],
    __v: 0,
  },
  {
    name: "来一碗麻辣烫",
    address: "广东省广州市越秀区中山五路219号华联购物中心F1",
    id: 1,
    latitude: 23.12497,
    longitude: 113.26308,
    location: [113.26308, 23.12497],
    phone: "13437850035",
    category: "快餐便当/简餐",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5a5859a19c2bc57d52df30b3",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5a5859a19c2bc57d52df30b2",
      },
      {
        description: "该商家支持开发票，请在下单时填写好发票抬头",
        icon_color: "999999",
        icon_name: "票",
        id: 4,
        name: "开发票",
        _id: "5a5859a19c2bc57d52df30b1",
      },
    ],
    status: 1,
    recent_order_num: 106,
    rating_count: 961,
    rating: 4.7,
    promotion_info: "欢迎光临，用餐高峰请提前下单，谢谢",
    piecewise_agent_fee: { tips: "配送费约¥5" },
    opening_hours: ["8:30/20:30"],
    license: {
      catering_service_license_image: "160e91e17fa2164.png",
      business_license_image: "160e91e0a9f2163.png",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_1.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 20,
    float_delivery_fee: 5,
    distance: "9.1公里",
    order_lead_time: "26分钟",
    description: "sad",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [],
    __v: 0,
  },
  {
    name: "地道味麻辣香锅",
    address: "阿联酋防守打法手动阀",
    id: 3269,
    latitude: 22.784219,
    longitude: 113.836478,
    location: [113.76077, 34.73822],
    phone: "110233qaqqq是打发的所发生的发地方广胜多负少东省浮动三个11236",
    category: "小吃夜宵/烧烤",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5bfc9a30d51a913e8655d397",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5bfc9a30d51a913e8655d396",
      },
      {
        description: "该商家支持开发票，请在下单时填写好发票抬头",
        icon_color: "999999",
        icon_name: "票",
        id: 4,
        name: "开发票",
        _id: "5bfc9a30d51a913e8655d395",
      },
    ],
    status: 0,
    recent_order_num: 100,
    rating_count: 218,
    rating: 5,
    promotion_info: "欢迎光临，用餐高峰请提前下单，谢谢",
    piecewise_agent_fee: { tips: "配送费约¥5" },
    opening_hours: ["06:30/09:00"],
    license: {
      catering_service_license_image: "",
      business_license_image: "",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_2.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 20,
    float_delivery_fee: 5,
    distance: "85公里",
    order_lead_time: "1小时14分钟",
    description: " 欢迎购买本店招牌菜：肉蛋葱鸡22阿斯顿发发发士大夫是",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [
      {
        icon_name: "减",
        name: "满减优惠",
        description: "满30减5，满60减8",
        icon_color: "f07373",
        id: 1,
        _id: "5bfc9a30d51a913e8655d398",
      },
    ],
    __v: 0,
  },
  {
    name: "健康早餐油条豆浆",
    address: "上海市浦东新区人民东路",
    id: 3276,
    latitude: 31.049617,
    longitude: 121.768129,
    location: [104.073498, 30.697163],
    phone: "150809608",
    category: "甜品饮品",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5bfcbf78d51a913e8655d4f4",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5bfcbf78d51a913e8655d4f3",
      },
      {
        description: "该商家支持开发票，请在下单时填写好发票抬头",
        icon_color: "999999",
        icon_name: "票",
        id: 4,
        name: "开发票",
        _id: "5bfcbf78d51a913e8655d4f2",
      },
    ],
    status: 1,
    recent_order_num: 831,
    rating_count: 482,
    rating: 4.1,
    promotion_info: "欢迎光临，用餐高峰请提前下单，谢谢",
    piecewise_agent_fee: { tips: "配送费约¥5" },
    opening_hours: ["8:30/20:30"],
    license: {
      catering_service_license_image: "",
      business_license_image: "",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_3.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 20,
    float_delivery_fee: 5,
    distance: "1405.4公里",
    order_lead_time: "14小时59分钟",
    description: "vue",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [
      {
        icon_name: "减",
        name: "满减优惠",
        description: "满30减5，满60减8",
        icon_color: "f07373",
        id: 1,
        _id: "5bfcbf78d51a913e8655d4f5",
      },
    ],
    __v: 0,
  },
  {
    name: "张姐烤肉饭",
    address: "rqwerqwer",
    id: 3278,
    latitude: 23.031723,
    longitude: 113.159088,
    location: [114.045515, 22.609881],
    phone: "13526347214",
    category: "快餐便当/简餐",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5bfcfda5d51a913e8655d735",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5bfcfda5d51a913e8655d734",
      },
    ],
    status: 1,
    recent_order_num: 601,
    rating_count: 909,
    rating: 4.3,
    promotion_info: "12345",
    piecewise_agent_fee: { tips: "配送费约¥1" },
    opening_hours: ["17:00/23:15"],
    license: {
      catering_service_license_image: "167543e718022786.jpeg",
      business_license_image: "167543e555722785.jpeg",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_4.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 5,
    float_delivery_fee: 1,
    distance: "23.4公里",
    order_lead_time: "35分钟",
    description: "无",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [
      {
        icon_name: "减",
        name: "满减优惠",
        description: "满30减5，满60减8",
        icon_color: "f07373",
        id: 1,
        _id: "5bfcfda5d51a913e8655d737",
      },
      {
        icon_name: "新",
        name: "新用户立减",
        description: "新用户ji-----",
        icon_color: "70bc46",
        id: 2,
        _id: "5bfcfda5d51a913e8655d736",
      },
    ],
    __v: 0,
  },
  {
    name: "萨沐丁",
    address: "广东省佛山市南海区 顶顶顶v佛挡杀佛",
    id: 3281,
    latitude: 39.159705,
    longitude: 117.14878,
    location: [116.436501, 39.950855],
    phone: "777积分工会法规股份合1计",
    category: "异国料理/披萨意面",
    supports: [
      {
        description: "已加入“外卖保”计划，食品安全有保障",
        icon_color: "999999",
        icon_name: "保",
        id: 7,
        name: "外卖保",
        _id: "5bfd02ded51a913e8655d7b9",
      },
      {
        description: "准时必达，超时秒赔",
        icon_color: "57A9FF",
        icon_name: "准",
        id: 9,
        name: "准时达",
        _id: "5bfd02ded51a913e8655d7b8",
      },
      {
        description: "该商家支持开发票，请在下单时填写好发票抬头",
        icon_color: "999999",
        icon_name: "票",
        id: 4,
        name: "开发票",
        _id: "5bfd02ded51a913e8655d7b7",
      },
    ],
    status: 0,
    recent_order_num: 636,
    rating_count: 247,
    rating: 4.6,
    promotion_info: "欢迎光临，用餐高峰请提前下单，谢谢",
    piecewise_agent_fee: { tips: "配送费约¥5" },
    opening_hours: ["8:30/20:30"],
    license: {
      catering_service_license_image: "",
      business_license_image: "",
    },
    is_new: true,
    is_premium: true,
    image_path: "https://gitee.com/xskss/image/raw/master/image_path_5.jpg",
    identification: {
      registered_number: "",
      registered_address: "",
      operation_period: "",
      licenses_scope: "",
      licenses_number: "",
      licenses_date: "",
      legal_person: "",
      identificate_date: null,
      identificate_agency: "",
      company_name: "",
    },
    float_minimum_order_amount: 20,
    float_delivery_fee: 5,
    distance: "2051.7公里",
    order_lead_time: "21小时43分钟",
    description: "能能能能能能能能能能能",
    delivery_mode: {
      color: "57A9FF",
      id: 1,
      is_solid: true,
      text: "蜂鸟专送",
    },
    activities: [
      {
        icon_name: "减",
        name: "满减优惠",
        description: "满30减5，满60减8",
        icon_color: "f07373",
        id: 1,
        _id: "5bfd02ded51a913e8655d7ba",
      },
    ],
    __v: 0,
  },
];
